{{- if .Values.dbadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frenchrevolution.fullname" . }}-dbadmin
  labels:
    {{- include "frenchrevolution.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dbadmin.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frenchrevolution.name" . }}-dbadmin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "frenchrevolution.name" . }}-dbadmin
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: dbadmin
          image: "{{ .Values.dbadmin.image.repository }}:{{ .Values.dbadmin.image.tag }}"
          imagePullPolicy: {{ .Values.dbadmin.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.dbadmin.service.targetPort }}
          env:
          - name: PGADMIN_DEFAULT_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ include "frenchrevolution.fullname" . }}-secret
                key: adminEmail
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "frenchrevolution.fullname" . }}-secret
                key: adminPassword
  {{- end }}