_dbUser: &dbUser ""
_dbPassword: &dbPassword ""
_dbName: &dbName ""

postgresql:
  auth:
    username: *dbUser
    password: *dbPassword
    database: *dbName

secrets:
  dbUser: *dbUser
  dbPassword: *dbPassword
  dbName: *dbName
  adminEmail: ""
  adminPassword: ""
  jwtSecret: ""
  mediatorLicense: ""