ingress:
  enabled: true
  className: "nginx" 
  api:
    host: "api.french-revolution.local"
    path: /
    pathType: Prefix
  dashboard:
    host: "dashboard.french-revolution.local"
    path: /
    pathType: Prefix
  dbadmin:
    host: "db-admin.french-revolution.local"
    path: /
    pathType: Prefix

api:
  replicaCount: 1
  image:
    repository: clashmarr/frenchrevolution
    tag: dev
    pullPolicy: Always
  service:
    port: 5000
    targetPort: 5000
  config:
    ASPNETCORE_ENVIRONMENT: "Development"
    ASPNETCORE_HTTP_PORTS: "5000"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://api-dashboard:18889"
    Jwt__Issuer: "http://localhost:5000"
    Jwt__Audience: "http://localhost:5000"
    Jwt__ExpireInMinutes: "2"
    DB_HOST: "db"
    DB_PORT: "5432"
    ConnectionStrings__Cache: "cache-master:6379"

postgresql:
  enabled: true
  fullnameOverride: db
  primary:
    service:
      port: 5432
      targetPort: 5432
    persistence:
      enabled: false

redis:
  enabled: true
  fullnameOverride: cache
  auth: 
    enabled: false
  master:
    service:
      port: 6379
      targetPort: 6379
  
dashboard:
  enabled: true
  replicaCount: 1
  image:
    repository: mcr.microsoft.com/dotnet/aspire-dashboard
    tag: "13"
    pullPolicy: IfNotPresent
  service: 
    port: 18888         
    targetPort: 18888
  otlp:
    service:
      port: 18889
      targetPort: 18889
      
dbadmin:
  enabled: true
  replicaCount: 1
  image:
    repository: dpage/pgadmin4
    tag: "9"
    pullPolicy: IfNotPresent
  service:
    port: 80
    targetPort: 80
  
  