apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frenchrevolution.fullname" . }}-config
  labels:
    {{- include "frenchrevolution.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.api.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}