apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frenchrevolution.fullname" . }}-secret
  labels:
    {{- include "frenchrevolution.labels" . | nindent 4 }}
type: Opaque
stringData:
  dbUser: {{ .Values.secrets.dbUser | quote }}
  dbPassword: {{ .Values.secrets.dbPassword | quote }}
  dbName: {{ .Values.secrets.dbName | quote }}
  adminEmail: {{ .Values.secrets.adminEmail | quote }}
  adminPassword: {{ .Values.secrets.adminPassword | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  mediatorLicense: {{ .Values.secrets.mediatorLicense | quote }}